# Generated by Django 5.2.8 on 2025-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
    ]
